### ISSUE TITLE
Support "odf" engine to create OpenDocument format (ods) files

### ISSUE THREAD

**Issue by buhtzz** [DeepSpace2/StyleFrame#128]
I am aware that currently only `openpyxl` is supported.

But for the FOSS community it would be great to have an open and more free format supported also. This would be the `odf` engine that can crate `ods` files.

**Comment by DeepSpace2** [comment]
Is this really necessary? As far as I know both LibreOffice and openoffice can read and write `xlsx` files.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Yes it is necessary because none of them implement the "standard" of the other side 100%.
The microsoft "standard" document is ~ 6.000 pages long. It is explicit complex to make it as hard as possible for others to implement their "standard".
On the other side microsoft don't implement the full OpenDocument standard.
