### ISSUE TITLE
Warning -- 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by guinslym** [DeepSpace2/StyleFrame#64]
Hi! I am getting this Warning:

> /Users/laptop89/Library/Caches/pypoetry/virtualenvs/project-trying-1A85ZMfm-py3.7/lib/python3.7/site-packages/StyleFrame/style_frame.py:11: DeprecationWarning:Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

$ poetry run python -V
Python 3.7.4

[[package]]
category = "main"
description = "A library that wraps pandas and openpyxl and allows easy styling of dataframes in excel. Documentation can be found at http://styleframe.readthedocs.org"
name = "styleframe"
optional = false
python-versions = "*"
version = "2.0.5"

**Comment by DeepSpace2** [comment]
Hi. This deprecation is coming due to an import within Python's standard lib and can be ignored.

**Comment by christian-oudard** [comment]
This is a compatibility issue with python 3.9. Please reopen and fix this.

**Comment by DeepSpace2** [comment]
@christian-oudard Thanks, had a second look and the import in the dependency had been fixed.

I also found 1 "old" import in StyleFrame code, which will be fixed in the next version.

In `style_frame.py`, `from collections import Iterable` should be changed to `from collections.abc import Iterable`.

**Comment by christian-oudard** [comment]
Thanks!
