### ISSUE TITLE
read_excel_as_template don't work properly

### ISSUE THREAD

**Issue by lfjbb** [DeepSpace2/StyleFrame#86]
[test.xlsx](https://github.com/DeepSpace2/StyleFrame/files/5259091/test.xlsx)

I have a template with a num_format like this:
![image](https://user-images.githubusercontent.com/35714131/93842572-f78c1400-fcc9-11ea-97c3-e2e7563ad4eb.png)

but the oupput is general:
![image](https://user-images.githubusercontent.com/35714131/93842535-df1bf980-fcc9-11ea-9930-d3e3450629e8.png)

I also print the column style and cell style, the column style is right but the cell style is not:
![image](https://user-images.githubusercontent.com/35714131/93842508-cca1c000-fcc9-11ea-9fa1-7d26eea0127f.png)

**Comment by DeepSpace2** [comment]
Hi.
It looks like in the first image the shown number format is of cell B4, which is empty.
As such, it is not even loaded when the sheet is read (since `pandas.read_excel` does not read more than it needs).

Also, in the second image, it looks like the shown number format is of cell B2 which is also empty.
