### ISSUE TITLE
set cell value result in setting the whole column etc.

### ISSUE THREAD

**Issue by tyker1** [DeepSpace2/StyleFrame#99]
first of all, i hope that you still has your eye on this project.

i'm using the most up-to-date version from your StyleFrame via pip install -U option

but came across with the issue that it cannot really modify the dataframe as the pandas one do, for instance i have following code that marks every row, that contains a cell with non standard color:

```python
sf['isMarked'] = 0
print(sf.loc[1,'isMarked'].style)
for rowIdx in range(1,sf.data_df.shape[0]):
    for columnName in sf.columns:
        if columnName == "isMarked":
            break
        if (sf.at[rowIdx, columnName].style.bg_color not in {utils.colors.white, 'ffffff','00000000'}) or (sf.at[rowIdx, columnName].style.font_color not in {utils.colors.black, '000000'}):
        #    print("idx=[{},{}]={}\t".format(columnName,rowIdx, sf.at[rowIdx, columnName].value))
        #    print(sf.at[rowIdx, columnName].style)
        #    print("\n\n")
            sf.loc[rowIdx, 'isMarked'].value = 1
            break
```

(note: don't ask me why bg_color not in white, ffffff and 000000, your frame returns the bg_color for the same cell (background set to not filled in excel) once '00000000' and once 'ffffff', completely random behavior.

if i use `sf.loc[rowIdx, 'isMarked'].value = 1`, what i get is the whole column for the table been set to 1. But not trouble with saving the sheet using your excelwriter.

However, if i drop the value and use `sf.loc[rowIdx, 'isMarked'] = 1` instead, it works fine by setting the column 'isMarked' of the given row to 1, but when saving the result, it says: `'int' object has no attribute 'style'`

also your document site is really lacking tons of information about your work. It is far less than enough to just list those methods from your self, since StyleFrame DO NOT support all the function of pandas dataframe, at least if people not knowing that they can access the pandas dataframe through the attribute `data_df` which is not listed in your documentation site.

**Comment by tyker1** [comment]
my dirty solution for the issue is to create a new styleframe from the modified dataframe of `sf`. However, i don't think this is a good solution people using styleframe as an advanced pandas dataframe.

It this is meant to be so, please mention it somewhere in the doc

**Comment by DeepSpace2** [comment]
- > if i use `sf.loc[rowIdx, 'isMarked'].value = 1`, what i get is the whole column for the table been set to 1

   I'm not sure I understand what you mean. Consider this example:
   ```
   df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
   sf = StyleFrame(df)
   sf.loc[1, 'a'].value = 99
   print(sf)  
  ```
  This outputs

  ```
      a  b  c
  0   1  4  7
  1  99  5  8
  2   3  6  9
  ```

  So it does not change the entire column.

- As you noticed, using pandas methods on the underlying dataframe (the `data_df` attribute) will break exporting to Excel since obviously they all return a dataframe and not a StyleFrame object with all the required underlying information.

- As such, it is considered best to do as much as data-mangling as possible before creating the StyleFrame object. I'm considering deprecating `data_df` and perhaps changing it to `_data_df` so it will be clearer that it is preferable to not directly mess with it.
